import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-business-personal-property-tax-recovery",
  "engine": "recovery",
  "title": "Business Personal Property Tax Recovery",
  "shortTitle": "Business Personal Property Tax Recovery",
  "tagline": "Reduce business-personal-property assessments through asset cleansing, situs, depreciation, exemption, and obsolescence evidence.",
  "industry": "Property Tax Recovery",
  "buyer": "Asset-intensive businesses and tax departments",
  "uiPort": 4682,
  "apiPort": 5682,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Business Personal Property Tax Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds in one accountable workflow. Reduce business-personal-property assessments through asset cleansing, situs, depreciation, exemption, and obsolescence evidence.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Business Personal Property Tax Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("asset-register-ingestion","BPP01","Asset register ingestion","Execute asset register ingestion using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed asset register ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Asset register ingestion Reference","text","BPP01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("location-situs-validation","BPP02","Location situs validation","Execute location situs validation using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed location situs validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Location situs validation Reference","text","BPP02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("ghost-asset-detection","BPP03","Ghost asset detection","Execute ghost asset detection using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed ghost asset detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Ghost asset detection Reference","text","BPP03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("disposed-asset-removal","BPP04","Disposed asset removal","Execute disposed asset removal using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed disposed asset removal decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Disposed asset removal Reference","text","BPP04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("asset-class-mapping","BPP05","Asset class mapping","Execute asset class mapping using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed asset class mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Asset class mapping Reference","text","BPP05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("depreciation-schedule-application","BPP06","Depreciation schedule application","Execute depreciation schedule application using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed depreciation schedule application decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Depreciation schedule application Reference","text","BPP06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("functional-obsolescence","BPP07","Functional obsolescence","Execute functional obsolescence using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed functional obsolescence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Functional obsolescence Reference","text","BPP07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("economic-obsolescence","BPP08","Economic obsolescence","Execute economic obsolescence using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed economic obsolescence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Economic obsolescence Reference","text","BPP08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("exemption-qualification","BPP09","Exemption qualification","Execute exemption qualification using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed exemption qualification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Exemption qualification Reference","text","BPP09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("rendition-preparation","BPP10","Rendition preparation","Execute rendition preparation using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed rendition preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Rendition preparation Reference","text","BPP10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("assessment-reconciliation","BPP11","Assessment reconciliation","Execute assessment reconciliation using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed assessment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Assessment reconciliation Reference","text","BPP11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("appeal-opportunity-scoring","BPP12","Appeal opportunity scoring","Execute appeal opportunity scoring using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed appeal opportunity scoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Appeal opportunity scoring Reference","text","BPP12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("evidence-packet-generation","BPP13","Evidence packet generation","Execute evidence packet generation using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed evidence packet generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Evidence packet generation Reference","text","BPP13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("refund-tracking","BPP14","Refund tracking","Execute refund tracking using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed refund tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Refund tracking Reference","text","BPP14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]}),
feature("jurisdiction-asset-analytics","BPP15","Jurisdiction asset analytics","Execute jurisdiction asset analytics using fixed asset registers, locations, acquisition costs, depreciation tables, exemptions, renditions, assessments, bills, appeals, and refunds.","Produce a governed jurisdiction asset analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Jurisdiction / Asset Account","text","Jurisdiction / Asset Account · Standard Case"],["caseReference","Jurisdiction asset analytics Reference","text","BPP15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1043750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1262938],["domainDriver","Asset Class","select","Machinery",["Machinery","Computer equipment","Furniture fixtures"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Asset register ingestion case","Location situs validation case","Ghost asset detection case","Disposed asset removal case","Asset class mapping case"]})
]);
